#!/bin/sh

bspc config border_width        4
bspc config window_gap         6

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

# Colors
bspc config active_border_color "#3F4B9C"
bspc config focused_border_color "#3F4B9C"
bspc config presel_border_color "#181818"
bspc config urgent_border_color "#C90515"
bspc config focused_locked_border_color "#8c644c"

# opacity
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc monitor HDMI1 -d I II III IV V
bspc monitor LVDS1 -d VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a feh floating=on
bspc rule -a urxvt floating=on
bspc rule -a uzbl-tabbed floating=on
bspc rule -a uzbl-core floating=on
bspc rule -a tilda floating=on

